"""扩充大学数据脚本 - 运行后更新 CSV 文件"""
import csv
import os

DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")

# 全国本科院校数据（按省份分组）
UNIVERSITIES = [
    # ===== 北京 =====
    ("北京大学", "北京", "北京", "综合", "985|211|双一流", "https://www.pku.edu.cn"),
    ("清华大学", "北京", "北京", "理工", "985|211|双一流", "https://www.tsinghua.edu.cn"),
    ("中国人民大学", "北京", "北京", "综合", "985|211|双一流", "https://www.ruc.edu.cn"),
    ("北京师范大学", "北京", "北京", "师范", "985|211|双一流", "https://www.bnu.edu.cn"),
    ("北京航空航天大学", "北京", "北京", "理工", "985|211|双一流", "https://www.buaa.edu.cn"),
    ("北京理工大学", "北京", "北京", "理工", "985|211|双一流", "https://www.bit.edu.cn"),
    ("中国农业大学", "北京", "北京", "农林", "985|211|双一流", "https://www.cau.edu.cn"),
    ("北京科技大学", "北京", "北京", "理工", "211|双一流", "https://www.ustb.edu.cn"),
    ("北京交通大学", "北京", "北京", "理工", "211|双一流", "https://www.bjtu.edu.cn"),
    ("北京邮电大学", "北京", "北京", "理工", "211|双一流", "https://www.bupt.edu.cn"),
    ("中央财经大学", "北京", "北京", "财经", "211|双一流", "https://www.cufe.edu.cn"),
    ("对外经济贸易大学", "北京", "北京", "财经", "211|双一流", "https://www.uibe.edu.cn"),
    ("北京外国语大学", "北京", "北京", "语言", "211|双一流", "https://www.bfsu.edu.cn"),
    ("中国政法大学", "北京", "北京", "政法", "211|双一流", "https://www.cupl.edu.cn"),
    ("北京工业大学", "北京", "北京", "理工", "211|双一流", "https://www.bjut.edu.cn"),
    ("华北电力大学", "北京", "北京", "理工", "211|双一流", "https://www.ncepu.edu.cn"),
    ("中国矿业大学（北京）", "北京", "北京", "理工", "211|双一流", "https://www.cumtb.edu.cn"),
    ("中国地质大学（北京）", "北京", "北京", "理工", "211|双一流", "https://www.cugb.edu.cn"),
    ("中国石油大学（北京）", "北京", "北京", "理工", "211|双一流", "https://www.cup.edu.cn"),
    ("北京化工大学", "北京", "北京", "理工", "211|双一流", "https://www.buct.edu.cn"),
    ("北京林业大学", "北京", "北京", "农林", "211|双一流", "https://www.bjfu.edu.cn"),
    ("北京中医药大学", "北京", "北京", "医药", "211|双一流", "https://www.bucm.edu.cn"),
    ("首都师范大学", "北京", "北京", "师范", "双一流", "https://www.cnu.edu.cn"),
    ("北京语言大学", "北京", "北京", "语言", "", "https://www.blcu.edu.cn"),
    ("中央民族大学", "北京", "北京", "民族", "985|211|双一流", "https://www.muc.edu.cn"),
    ("北京协和医学院", "北京", "北京", "医药", "双一流", "https://www.pumc.edu.cn"),
    ("首都医科大学", "北京", "北京", "医药", "", "https://www.ccmu.edu.cn"),
    ("北京工商大学", "北京", "北京", "财经", "", "https://www.btbu.edu.cn"),
    ("北京建筑大学", "北京", "北京", "理工", "", "https://www.bucea.edu.cn"),
    ("北京信息科技大学", "北京", "北京", "理工", "", "https://www.bistu.edu.cn"),
    ("北方工业大学", "北京", "北京", "理工", "", "https://www.ncut.edu.cn"),
    ("北京联合大学", "北京", "北京", "综合", "", "https://www.buu.edu.cn"),
    ("北京第二外国语学院", "北京", "北京", "语言", "", "https://www.bisu.edu.cn"),
    ("中国传媒大学", "北京", "北京", "语言", "211|双一流", "https://www.cuc.edu.cn"),
    ("中央音乐学院", "北京", "北京", "艺术", "211|双一流", "https://www.ccom.edu.cn"),
    ("中央美术学院", "北京", "北京", "艺术", "双一流", "https://www.cafa.edu.cn"),
    ("北京体育大学", "北京", "北京", "体育", "211|双一流", "https://www.bsu.edu.cn"),
    ("外交学院", "北京", "北京", "政法", "双一流", "https://www.cfau.edu.cn"),
    ("中国人民公安大学", "北京", "北京", "政法", "双一流", "https://www.ppsuc.edu.cn"),

    # ===== 上海 =====
    ("复旦大学", "上海", "上海", "综合", "985|211|双一流", "https://www.fudan.edu.cn"),
    ("上海交通大学", "上海", "上海", "综合", "985|211|双一流", "https://www.sjtu.edu.cn"),
    ("同济大学", "上海", "上海", "理工", "985|211|双一流", "https://www.tongji.edu.cn"),
    ("华东师范大学", "上海", "上海", "师范", "985|211|双一流", "https://www.ecnu.edu.cn"),
    ("华东理工大学", "上海", "上海", "理工", "211|双一流", "https://www.ecust.edu.cn"),
    ("上海大学", "上海", "上海", "综合", "211|双一流", "https://www.shu.edu.cn"),
    ("东华大学", "上海", "上海", "理工", "211|双一流", "https://www.dhu.edu.cn"),
    ("上海财经大学", "上海", "上海", "财经", "211|双一流", "https://www.shufe.edu.cn"),
    ("上海外国语大学", "上海", "上海", "语言", "211|双一流", "https://www.shisu.edu.cn"),
    ("华东政法大学", "上海", "上海", "政法", "", "https://www.ecupl.edu.cn"),
    ("上海师范大学", "上海", "上海", "师范", "", "https://www.shnu.edu.cn"),
    ("上海理工大学", "上海", "上海", "理工", "", "https://www.usst.edu.cn"),
    ("上海对外经贸大学", "上海", "上海", "财经", "", "https://www.suibe.edu.cn"),
    ("上海海洋大学", "上海", "上海", "农林", "双一流", "https://www.shou.edu.cn"),
    ("上海中医药大学", "上海", "上海", "医药", "双一流", "https://www.shutcm.edu.cn"),
    ("上海科技大学", "上海", "上海", "理工", "双一流", "https://www.shanghaitech.edu.cn"),
    ("上海纽约大学", "上海", "上海", "综合", "", "https://shanghai.nyu.edu"),
    ("上海体育大学", "上海", "上海", "体育", "双一流", "https://www.sus.edu.cn"),
    ("上海音乐学院", "上海", "上海", "艺术", "双一流", "https://www.shcmusic.edu.cn"),
    ("上海戏剧学院", "上海", "上海", "艺术", "", "https://www.sta.edu.cn"),

    # ===== 广东 =====
    ("中山大学", "广东", "广州", "综合", "985|211|双一流", "https://www.sysu.edu.cn"),
    ("华南理工大学", "广东", "广州", "理工", "985|211|双一流", "https://www.scut.edu.cn"),
    ("暨南大学", "广东", "广州", "综合", "211|双一流", "https://www.jnu.edu.cn"),
    ("华南师范大学", "广东", "广州", "师范", "211|双一流", "https://www.scnu.edu.cn"),
    ("华南农业大学", "广东", "广州", "农林", "双一流", "https://www.scau.edu.cn"),
    ("广州医科大学", "广东", "广州", "医药", "双一流", "https://www.gzhmu.edu.cn"),
    ("广州中医药大学", "广东", "广州", "医药", "双一流", "https://www.gzucm.edu.cn"),
    ("南方科技大学", "广东", "深圳", "理工", "双一流", "https://www.sustech.edu.cn"),
    ("深圳大学", "广东", "深圳", "综合", "", "https://www.szu.edu.cn"),
    ("广东工业大学", "广东", "广州", "理工", "", "https://www.gdut.edu.cn"),
    ("广州大学", "广东", "广州", "综合", "", "https://www.gzhu.edu.cn"),
    ("汕头大学", "广东", "汕头", "综合", "", "https://www.stu.edu.cn"),
    ("南方医科大学", "广东", "广州", "医药", "", "https://www.smu.edu.cn"),
    ("广东外语外贸大学", "广东", "广州", "语言", "", "https://www.gdufs.edu.cn"),
    ("广东财经大学", "广东", "广州", "财经", "", "https://www.gdufe.edu.cn"),
    ("广东海洋大学", "广东", "湛江", "农林", "", "https://www.gdou.edu.cn"),
    ("佛山科学技术学院", "广东", "佛山", "理工", "", "https://www.fosu.edu.cn"),
    ("东莞理工学院", "广东", "东莞", "理工", "", "https://www.dgut.edu.cn"),
    ("五邑大学", "广东", "江门", "综合", "", "https://www.wyu.edu.cn"),
    ("广东金融学院", "广东", "广州", "财经", "", "https://www.gduf.edu.cn"),
    ("岭南师范学院", "广东", "湛江", "师范", "", "https://www.lingnan.edu.cn"),
    ("韩山师范学院", "广东", "潮州", "师范", "", "https://www.hstc.edu.cn"),
    ("嘉应学院", "广东", "梅州", "综合", "", "https://www.jyu.edu.cn"),
    ("广东技术师范大学", "广东", "广州", "师范", "", "https://www.gpnu.edu.cn"),
    ("仲恺农业工程学院", "广东", "广州", "农林", "", "https://www.zhku.edu.cn"),
    ("广东药科大学", "广东", "广州", "医药", "", "https://www.gdpu.edu.cn"),
    ("广州美术学院", "广东", "广州", "艺术", "", "https://www.gzarts.edu.cn"),
    ("星海音乐学院", "广东", "广州", "艺术", "", "https://www.xhcom.edu.cn"),
    ("广州体育学院", "广东", "广州", "体育", "", "https://www.gipe.edu.cn"),
    ("哈尔滨工业大学（深圳）", "广东", "深圳", "理工", "985|211|双一流", "https://www.hitsz.edu.cn"),
    ("北京师范大学（珠海校区）", "广东", "珠海", "师范", "985|211|双一流", "https://www.bnu.edu.cn"),
    ("中山大学（深圳校区）", "广东", "深圳", "综合", "985|211|双一流", "https://www.sysu.edu.cn"),

    # ===== 江苏 =====
    ("南京大学", "江苏", "南京", "综合", "985|211|双一流", "https://www.nju.edu.cn"),
    ("东南大学", "江苏", "南京", "综合", "985|211|双一流", "https://www.seu.edu.cn"),
    ("南京航空航天大学", "江苏", "南京", "理工", "211|双一流", "https://www.nuaa.edu.cn"),
    ("南京理工大学", "江苏", "南京", "理工", "211|双一流", "https://www.njust.edu.cn"),
    ("河海大学", "江苏", "南京", "理工", "211|双一流", "https://www.hhu.edu.cn"),
    ("南京农业大学", "江苏", "南京", "农林", "211|双一流", "https://www.njau.edu.cn"),
    ("中国矿业大学", "江苏", "徐州", "理工", "211|双一流", "https://www.cumt.edu.cn"),
    ("南京师范大学", "江苏", "南京", "师范", "211|双一流", "https://www.njnu.edu.cn"),
    ("苏州大学", "江苏", "苏州", "综合", "211|双一流", "https://www.suda.edu.cn"),
    ("江南大学", "江苏", "无锡", "综合", "211|双一流", "https://www.jiangnan.edu.cn"),
    ("南京邮电大学", "江苏", "南京", "理工", "双一流", "https://www.njupt.edu.cn"),
    ("南京信息工程大学", "江苏", "南京", "理工", "双一流", "https://www.nuist.edu.cn"),
    ("南京林业大学", "江苏", "南京", "农林", "双一流", "https://www.njfu.edu.cn"),
    ("南京医科大学", "江苏", "南京", "医药", "双一流", "https://www.njmu.edu.cn"),
    ("南京中医药大学", "江苏", "南京", "医药", "双一流", "https://www.njucm.edu.cn"),
    ("中国药科大学", "江苏", "南京", "医药", "211|双一流", "https://www.cpu.edu.cn"),
    ("南京审计大学", "江苏", "南京", "财经", "", "https://www.nau.edu.cn"),
    ("南京财经大学", "江苏", "南京", "财经", "", "https://www.nufe.edu.cn"),
    ("南京工业大学", "江苏", "南京", "理工", "", "https://www.njtech.edu.cn"),
    ("江苏大学", "江苏", "镇江", "综合", "", "https://www.ujs.edu.cn"),
    ("扬州大学", "江苏", "扬州", "综合", "", "https://www.yzu.edu.cn"),
    ("南通大学", "江苏", "南通", "综合", "", "https://www.ntu.edu.cn"),
    ("江苏科技大学", "江苏", "镇江", "理工", "", "https://www.just.edu.cn"),
    ("常州大学", "江苏", "常州", "理工", "", "https://www.cczu.edu.cn"),
    ("徐州医科大学", "江苏", "徐州", "医药", "", "https://www.xzhmu.edu.cn"),
    ("江苏师范大学", "江苏", "徐州", "师范", "", "https://www.jsnu.edu.cn"),
    ("南京艺术学院", "江苏", "南京", "艺术", "", "https://www.nua.edu.cn"),
    ("苏州科技大学", "江苏", "苏州", "理工", "", "https://www.usts.edu.cn"),
    ("西交利物浦大学", "江苏", "苏州", "综合", "", "https://www.xjtlu.edu.cn"),
    ("昆山杜克大学", "江苏", "昆山", "综合", "", "https://dukekunshan.edu.cn"),

    # ===== 浙江 =====
    ("浙江大学", "浙江", "杭州", "综合", "985|211|双一流", "https://www.zju.edu.cn"),
    ("宁波大学", "浙江", "宁波", "综合", "双一流", "https://www.nbu.edu.cn"),
    ("浙江工业大学", "浙江", "杭州", "理工", "", "https://www.zjut.edu.cn"),
    ("浙江师范大学", "浙江", "金华", "师范", "", "https://www.zjnu.edu.cn"),
    ("杭州电子科技大学", "浙江", "杭州", "理工", "", "https://www.hdu.edu.cn"),
    ("浙江理工大学", "浙江", "杭州", "理工", "", "https://www.zstu.edu.cn"),
    ("浙江工商大学", "浙江", "杭州", "财经", "", "https://www.zjsu.edu.cn"),
    ("中国计量大学", "浙江", "杭州", "理工", "", "https://www.cjlu.edu.cn"),
    ("浙江中医药大学", "浙江", "杭州", "医药", "", "https://www.zcmu.edu.cn"),
    ("温州医科大学", "浙江", "温州", "医药", "", "https://www.wmu.edu.cn"),
    ("浙江财经大学", "浙江", "杭州", "财经", "", "https://www.zufe.edu.cn"),
    ("杭州师范大学", "浙江", "杭州", "师范", "", "https://www.hznu.edu.cn"),
    ("温州大学", "浙江", "温州", "综合", "", "https://www.wzu.edu.cn"),
    ("浙江农林大学", "浙江", "杭州", "农林", "", "https://www.zafu.edu.cn"),
    ("湖州师范学院", "浙江", "湖州", "师范", "", "https://www.zjhu.edu.cn"),
    ("绍兴文理学院", "浙江", "绍兴", "综合", "", "https://www.usx.edu.cn"),
    ("浙江海洋大学", "浙江", "舟山", "农林", "", "https://www.zjou.edu.cn"),
    ("中国美术学院", "浙江", "杭州", "艺术", "双一流", "https://www.caa.edu.cn"),
    ("宁波诺丁汉大学", "浙江", "宁波", "综合", "", "https://www.nottingham.edu.cn"),
    ("浙江传媒学院", "浙江", "杭州", "语言", "", "https://www.zjicm.edu.cn"),
    ("嘉兴学院", "浙江", "嘉兴", "综合", "", "https://www.zjxu.edu.cn"),
    ("浙江万里学院", "浙江", "宁波", "理工", "", "https://www.zwu.edu.cn"),
    ("丽水学院", "浙江", "丽水", "综合", "", "https://www.lsu.edu.cn"),
    ("台州学院", "浙江", "台州", "综合", "", "https://www.tzc.edu.cn"),
    ("衢州学院", "浙江", "衢州", "理工", "", "https://www.qzc.edu.cn"),

    # ===== 湖北 =====
    ("武汉大学", "湖北", "武汉", "综合", "985|211|双一流", "https://www.whu.edu.cn"),
    ("华中科技大学", "湖北", "武汉", "理工", "985|211|双一流", "https://www.hust.edu.cn"),
    ("华中师范大学", "湖北", "武汉", "师范", "211|双一流", "https://www.ccnu.edu.cn"),
    ("武汉理工大学", "湖北", "武汉", "理工", "211|双一流", "https://www.whut.edu.cn"),
    ("中国地质大学（武汉）", "湖北", "武汉", "理工", "211|双一流", "https://www.cug.edu.cn"),
    ("华中农业大学", "湖北", "武汉", "农林", "211|双一流", "https://www.hzau.edu.cn"),
    ("中南财经政法大学", "湖北", "武汉", "财经", "211|双一流", "https://www.zuel.edu.cn"),
    ("武汉科技大学", "湖北", "武汉", "理工", "", "https://www.wust.edu.cn"),
    ("湖北大学", "湖北", "武汉", "综合", "", "https://www.hubu.edu.cn"),
    ("中南民族大学", "湖北", "武汉", "民族", "", "https://www.scuec.edu.cn"),
    ("武汉工程大学", "湖北", "武汉", "理工", "", "https://www.wit.edu.cn"),
    ("湖北工业大学", "湖北", "武汉", "理工", "", "https://www.hbut.edu.cn"),
    ("武汉纺织大学", "湖北", "武汉", "理工", "", "https://www.wuse.edu.cn"),
    ("三峡大学", "湖北", "宜昌", "综合", "", "https://www.ctgu.edu.cn"),
    ("长江大学", "湖北", "荆州", "综合", "", "https://www.yangtzeu.edu.cn"),
    ("湖北师范大学", "湖北", "黄石", "师范", "", "https://www.hbnu.edu.cn"),
    ("武汉体育学院", "湖北", "武汉", "体育", "", "https://www.whsu.edu.cn"),
    ("湖北美术学院", "湖北", "武汉", "艺术", "", "https://www.hifa.edu.cn"),
    ("武汉音乐学院", "湖北", "武汉", "艺术", "", "https://www.whcm.edu.cn"),
    ("黄冈师范学院", "湖北", "黄冈", "师范", "", "https://www.hgnu.edu.cn"),
    ("湖北文理学院", "湖北", "襄阳", "综合", "", "https://www.hbuas.edu.cn"),
    ("湖北经济学院", "湖北", "武汉", "财经", "", "https://www.hbue.edu.cn"),
    ("江汉大学", "湖北", "武汉", "综合", "", "https://www.jhun.edu.cn"),

    # ===== 湖南 =====
    ("中南大学", "湖南", "长沙", "综合", "985|211|双一流", "https://www.csu.edu.cn"),
    ("湖南大学", "湖南", "长沙", "综合", "985|211|双一流", "https://www.hnu.edu.cn"),
    ("湖南师范大学", "湖南", "长沙", "师范", "211|双一流", "https://www.hunnu.edu.cn"),
    ("国防科技大学", "湖南", "长沙", "军事", "985|211|双一流", "https://www.nudt.edu.cn"),
    ("长沙理工大学", "湖南", "长沙", "理工", "", "https://www.csust.edu.cn"),
    ("湘潭大学", "湖南", "湘潭", "综合", "双一流", "https://www.xtu.edu.cn"),
    ("湖南农业大学", "湖南", "长沙", "农林", "", "https://www.hunau.edu.cn"),
    ("中南林业科技大学", "湖南", "长沙", "农林", "", "https://www.csuft.edu.cn"),
    ("湖南科技大学", "湖南", "湘潭", "综合", "", "https://www.hnust.edu.cn"),
    ("南华大学", "湖南", "衡阳", "综合", "", "https://www.usc.edu.cn"),
    ("湖南工业大学", "湖南", "株洲", "理工", "", "https://www.hut.edu.cn"),
    ("吉首大学", "湖南", "湘西", "综合", "", "https://www.jsu.edu.cn"),
    ("湖南中医药大学", "湖南", "长沙", "医药", "", "https://www.hnucm.edu.cn"),
    ("湖南工商大学", "湖南", "长沙", "财经", "", "https://www.hutb.edu.cn"),
    ("长沙学院", "湖南", "长沙", "综合", "", "https://www.ccsu.edu.cn"),
    ("湖南理工学院", "湖南", "岳阳", "理工", "", "https://www.hnist.edu.cn"),
    ("衡阳师范学院", "湖南", "衡阳", "师范", "", "https://www.hynu.edu.cn"),
    ("湖南文理学院", "湖南", "常德", "综合", "", "https://www.huas.edu.cn"),
    ("湖南工程学院", "湖南", "湘潭", "理工", "", "https://www.hnie.edu.cn"),
    ("湖南城市学院", "湖南", "益阳", "综合", "", "https://www.hncu.edu.cn"),
    ("长沙理工大学城南学院", "湖南", "长沙", "理工", "", "https://www.csust.edu.cn"),

    # ===== 四川 =====
    ("四川大学", "四川", "成都", "综合", "985|211|双一流", "https://www.scu.edu.cn"),
    ("电子科技大学", "四川", "成都", "理工", "985|211|双一流", "https://www.uestc.edu.cn"),
    ("西南交通大学", "四川", "成都", "理工", "211|双一流", "https://www.swjtu.edu.cn"),
    ("西南财经大学", "四川", "成都", "财经", "211|双一流", "https://www.swufe.edu.cn"),
    ("四川农业大学", "四川", "雅安", "农林", "211|双一流", "https://www.sicau.edu.cn"),
    ("成都理工大学", "四川", "成都", "理工", "双一流", "https://www.cdut.edu.cn"),
    ("西南石油大学", "四川", "成都", "理工", "双一流", "https://www.swpu.edu.cn"),
    ("成都中医药大学", "四川", "成都", "医药", "双一流", "https://www.cdutcm.edu.cn"),
    ("四川师范大学", "四川", "成都", "师范", "", "https://www.sicnu.edu.cn"),
    ("西南民族大学", "四川", "成都", "民族", "", "https://www.swun.edu.cn"),
    ("西南科技大学", "四川", "绵阳", "理工", "", "https://www.swust.edu.cn"),
    ("西华大学", "四川", "成都", "综合", "", "https://www.xhu.edu.cn"),
    ("成都信息工程大学", "四川", "成都", "理工", "", "https://www.cuit.edu.cn"),
    ("西华师范大学", "四川", "南充", "师范", "", "https://www.cwnu.edu.cn"),
    ("四川轻化工大学", "四川", "自贡", "理工", "", "https://www.suse.edu.cn"),
    ("中国民用航空飞行学院", "四川", "德阳", "理工", "", "https://www.cafuc.edu.cn"),
    ("西南医科大学", "四川", "泸州", "医药", "", "https://www.swmu.edu.cn"),
    ("川北医学院", "四川", "南充", "医药", "", "https://www.nsmc.edu.cn"),
    ("成都体育学院", "四川", "成都", "体育", "", "https://www.cdsu.edu.cn"),
    ("四川音乐学院", "四川", "成都", "艺术", "", "https://www.sccm.edu.cn"),
    ("四川美术学院", "四川", "重庆", "艺术", "", "https://www.scfai.edu.cn"),
    ("绵阳师范学院", "四川", "绵阳", "师范", "", "https://www.mtc.edu.cn"),
    ("内江师范学院", "四川", "内江", "师范", "", "https://www.njit.edu.cn"),
    ("宜宾学院", "四川", "宜宾", "综合", "", "https://www.yibinu.edu.cn"),
    ("攀枝花学院", "四川", "攀枝花", "综合", "", "https://www.pzhu.edu.cn"),

    # ===== 重庆 =====
    ("重庆大学", "重庆", "重庆", "综合", "985|211|双一流", "https://www.cqu.edu.cn"),
    ("西南大学", "重庆", "重庆", "综合", "211|双一流", "https://www.swu.edu.cn"),
    ("重庆邮电大学", "重庆", "重庆", "理工", "", "https://www.cqupt.edu.cn"),
    ("重庆交通大学", "重庆", "重庆", "理工", "", "https://www.cqjtu.edu.cn"),
    ("重庆医科大学", "重庆", "重庆", "医药", "", "https://www.cqmu.edu.cn"),
    ("重庆师范大学", "重庆", "重庆", "师范", "", "https://www.cqnu.edu.cn"),
    ("重庆工商大学", "重庆", "重庆", "财经", "", "https://www.ctbu.edu.cn"),
    ("重庆理工大学", "重庆", "重庆", "理工", "", "https://www.cqut.edu.cn"),
    ("重庆科技学院", "重庆", "重庆", "理工", "", "https://www.cqust.edu.cn"),
    ("四川外国语大学", "重庆", "重庆", "语言", "", "https://www.sisu.edu.cn"),
    ("西南政法大学", "重庆", "重庆", "政法", "", "https://www.swupl.edu.cn"),
    ("重庆文理学院", "重庆", "重庆", "综合", "", "https://www.cqwu.edu.cn"),
    ("长江师范学院", "重庆", "重庆", "师范", "", "https://www.yznu.edu.cn"),
    ("重庆三峡学院", "重庆", "重庆", "综合", "", "https://www.sanxiau.edu.cn"),

    # ===== 陕西 =====
    ("西安交通大学", "陕西", "西安", "综合", "985|211|双一流", "https://www.xjtu.edu.cn"),
    ("西北工业大学", "陕西", "西安", "理工", "985|211|双一流", "https://www.nwpu.edu.cn"),
    ("西安电子科技大学", "陕西", "西安", "理工", "211|双一流", "https://www.xidian.edu.cn"),
    ("西北大学", "陕西", "西安", "综合", "211|双一流", "https://www.nwu.edu.cn"),
    ("长安大学", "陕西", "西安", "理工", "211|双一流", "https://www.chd.edu.cn"),
    ("陕西师范大学", "陕西", "西安", "师范", "211|双一流", "https://www.snnu.edu.cn"),
    ("西北农林科技大学", "陕西", "咸阳", "农林", "985|211|双一流", "https://www.nwafu.edu.cn"),
    ("西安理工大学", "陕西", "西安", "理工", "", "https://www.xaut.edu.cn"),
    ("西安建筑科技大学", "陕西", "西安", "理工", "", "https://www.xauat.edu.cn"),
    ("西安科技大学", "陕西", "西安", "理工", "", "https://www.xust.edu.cn"),
    ("西安石油大学", "陕西", "西安", "理工", "", "https://www.xsyu.edu.cn"),
    ("陕西科技大学", "陕西", "西安", "理工", "", "https://www.sust.edu.cn"),
    ("西安工程大学", "陕西", "西安", "理工", "", "https://www.xpu.edu.cn"),
    ("西安工业大学", "陕西", "西安", "理工", "", "https://www.xatu.edu.cn"),
    ("西安外国语大学", "陕西", "西安", "语言", "", "https://www.xisu.edu.cn"),
    ("西北政法大学", "陕西", "西安", "政法", "", "https://www.nwupl.edu.cn"),
    ("西安邮电大学", "陕西", "西安", "理工", "", "https://www.xiyou.edu.cn"),
    ("西安财经大学", "陕西", "西安", "财经", "", "https://www.xufe.edu.cn"),
    ("延安大学", "陕西", "延安", "综合", "", "https://www.yau.edu.cn"),
    ("陕西中医药大学", "陕西", "咸阳", "医药", "", "https://www.sntcm.edu.cn"),
    ("西安医学院", "陕西", "西安", "医药", "", "https://www.xiyi.edu.cn"),
    ("西安文理学院", "陕西", "西安", "综合", "", "https://www.xawl.edu.cn"),
    ("宝鸡文理学院", "陕西", "宝鸡", "综合", "", "https://www.bjwlxy.edu.cn"),
    ("陕西理工大学", "陕西", "汉中", "理工", "", "https://www.snut.edu.cn"),
    ("西安美术学院", "陕西", "西安", "艺术", "", "https://www.xafa.edu.cn"),
    ("西安音乐学院", "陕西", "西安", "艺术", "", "https://www.xacom.edu.cn"),
    ("西安体育学院", "陕西", "西安", "体育", "", "https://www.xaipe.edu.cn"),

    # ===== 山东 =====
    ("山东大学", "山东", "济南", "综合", "985|211|双一流", "https://www.sdu.edu.cn"),
    ("中国海洋大学", "山东", "青岛", "综合", "985|211|双一流", "https://www.ouc.edu.cn"),
    ("中国石油大学（华东）", "山东", "青岛", "理工", "211|双一流", "https://www.upc.edu.cn"),
    ("山东师范大学", "山东", "济南", "师范", "", "https://www.sdnu.edu.cn"),
    ("青岛大学", "山东", "青岛", "综合", "", "https://www.qdu.edu.cn"),
    ("山东科技大学", "山东", "青岛", "理工", "", "https://www.sdust.edu.cn"),
    ("济南大学", "山东", "济南", "综合", "", "https://www.ujn.edu.cn"),
    ("山东农业大学", "山东", "泰安", "农林", "", "https://www.sdau.edu.cn"),
    ("曲阜师范大学", "山东", "曲阜", "师范", "", "https://www.qfnu.edu.cn"),
    ("山东财经大学", "山东", "济南", "财经", "", "https://www.sdufe.edu.cn"),
    ("青岛科技大学", "山东", "青岛", "理工", "", "https://www.qust.edu.cn"),
    ("山东理工大学", "山东", "淄博", "理工", "", "https://www.sdut.edu.cn"),
    ("烟台大学", "山东", "烟台", "综合", "", "https://www.ytu.edu.cn"),
    ("山东中医药大学", "山东", "济南", "医药", "", "https://www.sdutcm.edu.cn"),
    ("鲁东大学", "山东", "烟台", "综合", "", "https://www.ldu.edu.cn"),
    ("聊城大学", "山东", "聊城", "综合", "", "https://www.lcu.edu.cn"),
    ("青岛理工大学", "山东", "青岛", "理工", "", "https://www.qtech.edu.cn"),
    ("山东建筑大学", "山东", "济南", "理工", "", "https://www.sdjzu.edu.cn"),
    ("齐鲁工业大学", "山东", "济南", "理工", "", "https://www.qlu.edu.cn"),
    ("临沂大学", "山东", "临沂", "综合", "", "https://www.lyu.edu.cn"),
    ("山东第一医科大学", "山东", "济南", "医药", "", "https://www.sdfmu.edu.cn"),
    ("潍坊医学院", "山东", "潍坊", "医药", "", "https://www.wfmc.edu.cn"),
    ("滨州医学院", "山东", "滨州", "医药", "", "https://www.bzmc.edu.cn"),
    ("济宁医学院", "山东", "济宁", "医药", "", "https://www.jnmc.edu.cn"),
    ("山东工艺美术学院", "山东", "济南", "艺术", "", "https://www.sdada.edu.cn"),
    ("山东艺术学院", "山东", "济南", "艺术", "", "https://www.sdca.edu.cn"),
    ("山东体育学院", "山东", "济南", "体育", "", "https://www.sdpei.edu.cn"),

    # ===== 天津 =====
    ("南开大学", "天津", "天津", "综合", "985|211|双一流", "https://www.nankai.edu.cn"),
    ("天津大学", "天津", "天津", "理工", "985|211|双一流", "https://www.tju.edu.cn"),
    ("天津医科大学", "天津", "天津", "医药", "211|双一流", "https://www.tmu.edu.cn"),
    ("天津工业大学", "天津", "天津", "理工", "双一流", "https://www.tiangong.edu.cn"),
    ("天津中医药大学", "天津", "天津", "医药", "双一流", "https://www.tjutcm.edu.cn"),
    ("天津师范大学", "天津", "天津", "师范", "", "https://www.tjnu.edu.cn"),
    ("天津财经大学", "天津", "天津", "财经", "", "https://www.tjufe.edu.cn"),
    ("天津理工大学", "天津", "天津", "理工", "", "https://www.tjut.edu.cn"),
    ("天津科技大学", "天津", "天津", "理工", "", "https://www.tust.edu.cn"),
    ("中国民航大学", "天津", "天津", "理工", "", "https://www.cauc.edu.cn"),
    ("天津外国语大学", "天津", "天津", "语言", "", "https://www.tjfsu.edu.cn"),
    ("天津商业大学", "天津", "天津", "财经", "", "https://www.tjcu.edu.cn"),
    ("天津城建大学", "天津", "天津", "理工", "", "https://www.tcu.edu.cn"),
    ("天津体育学院", "天津", "天津", "体育", "", "https://www.tjus.edu.cn"),
    ("天津音乐学院", "天津", "天津", "艺术", "", "https://www.tjcm.edu.cn"),
    ("天津美术学院", "天津", "天津", "艺术", "", "https://www.tjarts.edu.cn"),
    ("天津农学院", "天津", "天津", "农林", "", "https://www.tjau.edu.cn"),
    ("天津职业技术师范大学", "天津", "天津", "师范", "", "https://www.tute.edu.cn"),

    # ===== 福建 =====
    ("厦门大学", "福建", "厦门", "综合", "985|211|双一流", "https://www.xmu.edu.cn"),
    ("福州大学", "福建", "福州", "理工", "211|双一流", "https://www.fzu.edu.cn"),
    ("福建师范大学", "福建", "福州", "师范", "", "https://www.fjnu.edu.cn"),
    ("福建农林大学", "福建", "福州", "农林", "", "https://www.fafu.edu.cn"),
    ("华侨大学", "福建", "泉州", "综合", "", "https://www.hqu.edu.cn"),
    ("集美大学", "福建", "厦门", "综合", "", "https://www.jmu.edu.cn"),
    ("福建医科大学", "福建", "福州", "医药", "", "https://www.fjmu.edu.cn"),
    ("福建中医药大学", "福建", "福州", "医药", "", "https://www.fjtcm.edu.cn"),
    ("闽南师范大学", "福建", "漳州", "师范", "", "https://www.mnnu.edu.cn"),
    ("福建工程学院", "福建", "福州", "理工", "", "https://www.fjut.edu.cn"),
    ("厦门理工学院", "福建", "厦门", "理工", "", "https://www.xmut.edu.cn"),
    ("闽江学院", "福建", "福州", "综合", "", "https://www.mju.edu.cn"),
    ("泉州师范学院", "福建", "泉州", "师范", "", "https://www.qztc.edu.cn"),
    ("福建江夏学院", "福建", "福州", "财经", "", "https://www.fjjxu.edu.cn"),
    ("龙岩学院", "福建", "龙岩", "综合", "", "https://www.lyun.edu.cn"),
    ("武夷学院", "福建", "南平", "综合", "", "https://www.wuyiu.edu.cn"),
    ("莆田学院", "福建", "莆田", "综合", "", "https://www.ptu.edu.cn"),

    # ===== 安徽 =====
    ("中国科学技术大学", "安徽", "合肥", "理工", "985|211|双一流", "https://www.ustc.edu.cn"),
    ("合肥工业大学", "安徽", "合肥", "理工", "211|双一流", "https://www.hfut.edu.cn"),
    ("安徽大学", "安徽", "合肥", "综合", "211|双一流", "https://www.ahu.edu.cn"),
    ("安徽师范大学", "安徽", "芜湖", "师范", "", "https://www.ahnu.edu.cn"),
    ("安徽医科大学", "安徽", "合肥", "医药", "", "https://www.ahmu.edu.cn"),
    ("安徽农业大学", "安徽", "合肥", "农林", "", "https://www.ahau.edu.cn"),
    ("安徽工业大学", "安徽", "马鞍山", "理工", "", "https://www.ahut.edu.cn"),
    ("安徽理工大学", "安徽", "淮南", "理工", "", "https://www.aust.edu.cn"),
    ("安徽财经大学", "安徽", "蚌埠", "财经", "", "https://www.aufe.edu.cn"),
    ("安徽建筑大学", "安徽", "合肥", "理工", "", "https://www.ahjzu.edu.cn"),
    ("安徽中医药大学", "安徽", "合肥", "医药", "", "https://www.ahtcm.edu.cn"),
    ("淮北师范大学", "安徽", "淮北", "师范", "", "https://www.chnu.edu.cn"),
    ("安徽工程大学", "安徽", "芜湖", "理工", "", "https://www.ahpu.edu.cn"),
    ("蚌埠医科大学", "安徽", "蚌埠", "医药", "", "https://www.bbmc.edu.cn"),
    ("安庆师范大学", "安徽", "安庆", "师范", "", "https://www.aqnu.edu.cn"),
    ("阜阳师范大学", "安徽", "阜阳", "师范", "", "https://www.fynu.edu.cn"),
    ("合肥学院", "安徽", "合肥", "综合", "", "https://www.hfuu.edu.cn"),
    ("铜陵学院", "安徽", "铜陵", "财经", "", "https://www.tlu.edu.cn"),
    ("皖南医学院", "安徽", "芜湖", "医药", "", "https://www.wnmc.edu.cn"),
    ("安徽科技学院", "安徽", "蚌埠", "理工", "", "https://www.ahstu.edu.cn"),

    # ===== 河南 =====
    ("郑州大学", "河南", "郑州", "综合", "211|双一流", "https://www.zzu.edu.cn"),
    ("河南大学", "河南", "开封", "综合", "双一流", "https://www.henu.edu.cn"),
    ("河南师范大学", "河南", "新乡", "师范", "", "https://www.htu.edu.cn"),
    ("河南农业大学", "河南", "郑州", "农林", "", "https://www.henau.edu.cn"),
    ("河南科技大学", "河南", "洛阳", "综合", "", "https://www.haust.edu.cn"),
    ("河南理工大学", "河南", "焦作", "理工", "", "https://www.hpu.edu.cn"),
    ("河南工业大学", "河南", "郑州", "理工", "", "https://www.haut.edu.cn"),
    ("华北水利水电大学", "河南", "郑州", "理工", "", "https://www.ncwu.edu.cn"),
    ("郑州轻工业大学", "河南", "郑州", "理工", "", "https://www.zzuli.edu.cn"),
    ("河南中医药大学", "河南", "郑州", "医药", "", "https://www.hactcm.edu.cn"),
    ("新乡医学院", "河南", "新乡", "医药", "", "https://www.xxmu.edu.cn"),
    ("信阳师范大学", "河南", "信阳", "师范", "", "https://www.xynu.edu.cn"),
    ("河南财经政法大学", "河南", "郑州", "财经", "", "https://www.huel.edu.cn"),
    ("中原工学院", "河南", "郑州", "理工", "", "https://www.zut.edu.cn"),
    ("郑州航空工业管理学院", "河南", "郑州", "理工", "", "https://www.zia.edu.cn"),
    ("洛阳理工学院", "河南", "洛阳", "理工", "", "https://www.lit.edu.cn"),
    ("南阳理工学院", "河南", "南阳", "理工", "", "https://www.nyist.edu.cn"),
    ("安阳师范学院", "河南", "安阳", "师范", "", "https://www.aynu.edu.cn"),
    ("南阳师范学院", "河南", "南阳", "师范", "", "https://www.nynu.edu.cn"),
    ("洛阳师范学院", "河南", "洛阳", "师范", "", "https://www.lynu.edu.cn"),
    ("商丘师范学院", "河南", "商丘", "师范", "", "https://www.sqnu.edu.cn"),
    ("周口师范学院", "河南", "周口", "师范", "", "https://www.zknu.edu.cn"),
    ("许昌学院", "河南", "许昌", "综合", "", "https://www.xcu.edu.cn"),
    ("黄淮学院", "河南", "驻马店", "综合", "", "https://www.huanghuai.edu.cn"),
    ("平顶山学院", "河南", "平顶山", "综合", "", "https://www.pdsu.edu.cn"),
    ("河南城建学院", "河南", "平顶山", "理工", "", "https://www.hncj.edu.cn"),
    ("河南牧业经济学院", "河南", "郑州", "农林", "", "https://www.hnuahe.edu.cn"),
    ("郑州师范学院", "河南", "郑州", "师范", "", "https://www.zznu.edu.cn"),

    # ===== 河北 =====
    ("河北工业大学", "河北", "天津", "理工", "211|双一流", "https://www.hebut.edu.cn"),
    ("燕山大学", "河北", "秦皇岛", "综合", "", "https://www.ysu.edu.cn"),
    ("河北大学", "河北", "保定", "综合", "", "https://www.hbu.edu.cn"),
    ("河北师范大学", "河北", "石家庄", "师范", "", "https://www.hebtu.edu.cn"),
    ("河北医科大学", "河北", "石家庄", "医药", "", "https://www.hebmu.edu.cn"),
    ("河北农业大学", "河北", "保定", "农林", "", "https://www.hebau.edu.cn"),
    ("石家庄铁道大学", "河北", "石家庄", "理工", "", "https://www.stdu.edu.cn"),
    ("河北科技大学", "河北", "石家庄", "理工", "", "https://www.hebust.edu.cn"),
    ("华北理工大学", "河北", "唐山", "综合", "", "https://www.ncst.edu.cn"),
    ("河北工程大学", "河北", "邯郸", "理工", "", "https://www.hebeu.edu.cn"),
    ("河北经贸大学", "河北", "石家庄", "财经", "", "https://www.heuet.edu.cn"),
    ("河北地质大学", "河北", "石家庄", "理工", "", "https://www.hgu.edu.cn"),
    ("河北中医药大学", "河北", "石家庄", "医药", "", "https://www.hebcm.edu.cn"),
    ("承德医学院", "河北", "承德", "医药", "", "https://www.cdmc.edu.cn"),
    ("河北科技师范学院", "河北", "秦皇岛", "师范", "", "https://www.hevttc.edu.cn"),
    ("唐山师范学院", "河北", "唐山", "师范", "", "https://www.tstc.edu.cn"),
    ("廊坊师范学院", "河北", "廊坊", "师范", "", "https://www.lfnu.edu.cn"),
    ("邢台学院", "河北", "邢台", "综合", "", "https://www.xttc.edu.cn"),
    ("邯郸学院", "河北", "邯郸", "综合", "", "https://www.hdxy.edu.cn"),
    ("衡水学院", "河北", "衡水", "综合", "", "https://www.hsnc.edu.cn"),
    ("河北北方学院", "河北", "张家口", "综合", "", "https://www.hebeinu.edu.cn"),
    ("保定学院", "河北", "保定", "综合", "", "https://www.bdu.edu.cn"),
    ("张家口学院", "河北", "张家口", "综合", "", "https://www.zjku.edu.cn"),
    ("河北建筑工程学院", "河北", "张家口", "理工", "", "https://www.hebiace.edu.cn"),
    ("北华航天工业学院", "河北", "廊坊", "理工", "", "https://www.nciae.edu.cn"),
    ("防灾科技学院", "河北", "廊坊", "理工", "", "https://www.cidp.edu.cn"),
    ("河北体育学院", "河北", "石家庄", "体育", "", "https://www.hepec.edu.cn"),

    # ===== 辽宁 =====
    ("大连理工大学", "辽宁", "大连", "理工", "985|211|双一流", "https://www.dlut.edu.cn"),
    ("东北大学", "辽宁", "沈阳", "理工", "985|211|双一流", "https://www.neu.edu.cn"),
    ("大连海事大学", "辽宁", "大连", "理工", "211|双一流", "https://www.dlmu.edu.cn"),
    ("辽宁大学", "辽宁", "沈阳", "综合", "211|双一流", "https://www.lnu.edu.cn"),
    ("东北财经大学", "辽宁", "大连", "财经", "", "https://www.dufe.edu.cn"),
    ("大连医科大学", "辽宁", "大连", "医药", "", "https://www.dmu.edu.cn"),
    ("沈阳药科大学", "辽宁", "沈阳", "医药", "", "https://www.syphu.edu.cn"),
    ("辽宁师范大学", "辽宁", "大连", "师范", "", "https://www.lnnu.edu.cn"),
    ("大连交通大学", "辽宁", "大连", "理工", "", "https://www.djtu.edu.cn"),
    ("沈阳建筑大学", "辽宁", "沈阳", "理工", "", "https://www.sjzu.edu.cn"),
    ("大连工业大学", "辽宁", "大连", "理工", "", "https://www.dpu.edu.cn"),
    ("沈阳工业大学", "辽宁", "沈阳", "理工", "", "https://www.sut.edu.cn"),
    ("辽宁工程技术大学", "辽宁", "阜新", "理工", "", "https://www.lntu.edu.cn"),
    ("大连外国语大学", "辽宁", "大连", "语言", "", "https://www.dlufl.edu.cn"),
    ("大连大学", "辽宁", "大连", "综合", "", "https://www.dlu.edu.cn"),
    ("沈阳师范大学", "辽宁", "沈阳", "师范", "", "https://www.synu.edu.cn"),
    ("大连海洋大学", "辽宁", "大连", "农林", "", "https://www.dlou.edu.cn"),
    ("沈阳农业大学", "辽宁", "沈阳", "农林", "", "https://www.syau.edu.cn"),
    ("中国医科大学", "辽宁", "沈阳", "医药", "", "https://www.cmu.edu.cn"),
    ("辽宁中医药大学", "辽宁", "沈阳", "医药", "", "https://www.lnutcm.edu.cn"),
    ("大连民族大学", "辽宁", "大连", "民族", "", "https://www.dlnu.edu.cn"),
    ("沈阳航空航天大学", "辽宁", "沈阳", "理工", "", "https://www.sau.edu.cn"),
    ("沈阳理工大学", "辽宁", "沈阳", "理工", "", "https://www.sylu.edu.cn"),
    ("辽宁科技大学", "辽宁", "鞍山", "理工", "", "https://www.ustl.edu.cn"),
    ("辽宁石油化工大学", "辽宁", "抚顺", "理工", "", "https://www.lnpu.edu.cn"),
    ("沈阳化工大学", "辽宁", "沈阳", "理工", "", "https://www.syuct.edu.cn"),
    ("渤海大学", "辽宁", "锦州", "综合", "", "https://www.bhu.edu.cn"),
    ("锦州医科大学", "辽宁", "锦州", "医药", "", "https://www.jzmu.edu.cn"),
    ("沈阳音乐学院", "辽宁", "沈阳", "艺术", "", "https://www.sycm.edu.cn"),
    ("鲁迅美术学院", "辽宁", "沈阳", "艺术", "", "https://www.lumei.edu.cn"),
    ("沈阳体育学院", "辽宁", "沈阳", "体育", "", "https://www.syty.edu.cn"),
    ("鞍山师范学院", "辽宁", "鞍山", "师范", "", "https://www.asnc.edu.cn"),
    ("辽东学院", "辽宁", "丹东", "综合", "", "https://www.ldxy.edu.cn"),

    # ===== 吉林 =====
    ("吉林大学", "吉林", "长春", "综合", "985|211|双一流", "https://www.jlu.edu.cn"),
    ("东北师范大学", "吉林", "长春", "师范", "211|双一流", "https://www.nenu.edu.cn"),
    ("延边大学", "吉林", "延边", "综合", "211|双一流", "https://www.ybu.edu.cn"),
    ("长春理工大学", "吉林", "长春", "理工", "", "https://www.cust.edu.cn"),
    ("东北电力大学", "吉林", "吉林", "理工", "", "https://www.neepu.edu.cn"),
    ("长春工业大学", "吉林", "长春", "理工", "", "https://www.ccut.edu.cn"),
    ("吉林农业大学", "吉林", "长春", "农林", "", "https://www.jlau.edu.cn"),
    ("长春中医药大学", "吉林", "长春", "医药", "", "https://www.ccucm.edu.cn"),
    ("吉林师范大学", "吉林", "四平", "师范", "", "https://www.jlnu.edu.cn"),
    ("吉林财经大学", "吉林", "长春", "财经", "", "https://www.jlufe.edu.cn"),
    ("北华大学", "吉林", "吉林", "综合", "", "https://www.beihua.edu.cn"),
    ("长春大学", "吉林", "长春", "综合", "", "https://www.ccu.edu.cn"),
    ("吉林建筑大学", "吉林", "长春", "理工", "", "https://www.jliae.edu.cn"),
    ("长春师范大学", "吉林", "长春", "师范", "", "https://www.ccsfu.edu.cn"),
    ("吉林工程技术师范学院", "吉林", "长春", "师范", "", "https://www.jltute.edu.cn"),
    ("通化师范学院", "吉林", "通化", "师范", "", "https://www.thnu.edu.cn"),
    ("白城师范学院", "吉林", "白城", "师范", "", "https://www.bcsfxy.edu.cn"),
    ("吉林化工学院", "吉林", "吉林", "理工", "", "https://www.jlict.edu.cn"),
    ("吉林医药学院", "吉林", "吉林", "医药", "", "https://www.jlmu.edu.cn"),
    ("吉林体育学院", "吉林", "长春", "体育", "", "https://www.jlsu.edu.cn"),
    ("吉林艺术学院", "吉林", "长春", "艺术", "", "https://www.jlart.edu.cn"),
    ("吉林农业科技学院", "吉林", "吉林", "农林", "", "https://www.jlaas.edu.cn"),
    ("吉林工商学院", "吉林", "长春", "财经", "", "https://www.jlbtc.edu.cn"),

    # ===== 黑龙江 =====
    ("哈尔滨工业大学", "黑龙江", "哈尔滨", "理工", "985|211|双一流", "https://www.hit.edu.cn"),
    ("哈尔滨工程大学", "黑龙江", "哈尔滨", "理工", "211|双一流", "https://www.hrbeu.edu.cn"),
    ("东北林业大学", "黑龙江", "哈尔滨", "农林", "211|双一流", "https://www.nefu.edu.cn"),
    ("东北农业大学", "黑龙江", "哈尔滨", "农林", "211|双一流", "https://www.neau.edu.cn"),
    ("黑龙江大学", "黑龙江", "哈尔滨", "综合", "", "https://www.hlju.edu.cn"),
    ("哈尔滨医科大学", "黑龙江", "哈尔滨", "医药", "", "https://www.hrbmu.edu.cn"),
    ("哈尔滨理工大学", "黑龙江", "哈尔滨", "理工", "", "https://www.hrbust.edu.cn"),
    ("东北石油大学", "黑龙江", "大庆", "理工", "", "https://www.nepu.edu.cn"),
    ("哈尔滨师范大学", "黑龙江", "哈尔滨", "师范", "", "https://www.hrbnu.edu.cn"),
    ("哈尔滨商业大学", "黑龙江", "哈尔滨", "财经", "", "https://www.hrbcu.edu.cn"),
    ("黑龙江中医药大学", "黑龙江", "哈尔滨", "医药", "", "https://www.hljucm.edu.cn"),
    ("齐齐哈尔大学", "黑龙江", "齐齐哈尔", "综合", "", "https://www.qqhru.edu.cn"),
    ("黑龙江科技大学", "黑龙江", "哈尔滨", "理工", "", "https://www.usth.edu.cn"),
    ("佳木斯大学", "黑龙江", "佳木斯", "综合", "", "https://www.jmsu.edu.cn"),
    ("黑龙江八一农垦大学", "黑龙江", "大庆", "农林", "", "https://www.byau.edu.cn"),
    ("牡丹江医学院", "黑龙江", "牡丹江", "医药", "", "https://www.mdjmu.edu.cn"),
    ("齐齐哈尔医学院", "黑龙江", "齐齐哈尔", "医药", "", "https://www.qqhrmu.edu.cn"),
    ("牡丹江师范学院", "黑龙江", "牡丹江", "师范", "", "https://www.mdjnu.edu.cn"),
    ("大庆师范学院", "黑龙江", "大庆", "师范", "", "https://www.dqsy.edu.cn"),
    ("绥化学院", "黑龙江", "绥化", "综合", "", "https://www.shxy.edu.cn"),
    ("黑河学院", "黑龙江", "黑河", "综合", "", "https://www.hhxy.edu.cn"),
    ("哈尔滨体育学院", "黑龙江", "哈尔滨", "体育", "", "https://www.hrbipe.edu.cn"),
    ("哈尔滨音乐学院", "黑龙江", "哈尔滨", "艺术", "", "https://www.hrbc.edu.cn"),
    ("黑龙江工程学院", "黑龙江", "哈尔滨", "理工", "", "https://www.hljit.edu.cn"),
    ("哈尔滨金融学院", "黑龙江", "哈尔滨", "财经", "", "https://www.hrbfu.edu.cn"),
    ("黑龙江工业学院", "黑龙江", "鸡西", "理工", "", "https://www.hdyxy.edu.cn"),

    # ===== 江西 =====
    ("南昌大学", "江西", "南昌", "综合", "211|双一流", "https://www.ncu.edu.cn"),
    ("江西师范大学", "江西", "南昌", "师范", "", "https://www.jxnu.edu.cn"),
    ("江西财经大学", "江西", "南昌", "财经", "", "https://www.jxufe.edu.cn"),
    ("华东交通大学", "江西", "南昌", "理工", "", "https://www.ecjtu.edu.cn"),
    ("南昌航空大学", "江西", "南昌", "理工", "", "https://www.nchu.edu.cn"),
    ("江西理工大学", "江西", "赣州", "理工", "", "https://www.jxust.edu.cn"),
    ("东华理工大学", "江西", "抚州", "理工", "", "https://www.ecut.edu.cn"),
    ("江西农业大学", "江西", "南昌", "农林", "", "https://www.jxau.edu.cn"),
    ("江西中医药大学", "江西", "南昌", "医药", "", "https://www.jxutcm.edu.cn"),
    ("赣南医科大学", "江西", "赣州", "医药", "", "https://www.gmu.edu.cn"),
    ("井冈山大学", "江西", "吉安", "综合", "", "https://www.jgsu.edu.cn"),
    ("景德镇陶瓷大学", "江西", "景德镇", "理工", "", "https://www.jci.edu.cn"),
    ("赣南师范大学", "江西", "赣州", "师范", "", "https://www.gnnu.edu.cn"),
    ("江西科技师范大学", "江西", "南昌", "师范", "", "https://www.jxstnu.edu.cn"),
    ("南昌工程学院", "江西", "南昌", "理工", "", "https://www.nit.edu.cn"),
    ("宜春学院", "江西", "宜春", "综合", "", "https://www.ycu.edu.cn"),
    ("上饶师范学院", "江西", "上饶", "师范", "", "https://www.sru.jx.cn"),
    ("九江学院", "江西", "九江", "综合", "", "https://www.jju.edu.cn"),
    ("新余学院", "江西", "新余", "综合", "", "https://www.xyc.edu.cn"),
    ("萍乡学院", "江西", "萍乡", "综合", "", "https://www.pxc.edu.cn"),
    ("景德镇学院", "江西", "景德镇", "综合", "", "https://www.jcxy.edu.cn"),
    ("豫章师范学院", "江西", "南昌", "师范", "", "https://www.yztc.edu.cn"),
    ("南昌师范学院", "江西", "南昌", "师范", "", "https://www.nie.edu.cn"),
    ("江西警察学院", "江西", "南昌", "政法", "", "https://www.jxga.com"),
    ("南昌医学院", "江西", "南昌", "医药", "", "https://www.ncmc.edu.cn"),

    # ===== 广西 =====
    ("广西大学", "广西", "南宁", "综合", "211|双一流", "https://www.gxu.edu.cn"),
    ("广西师范大学", "广西", "桂林", "师范", "", "https://www.gxnu.edu.cn"),
    ("桂林电子科技大学", "广西", "桂林", "理工", "", "https://www.guet.edu.cn"),
    ("桂林理工大学", "广西", "桂林", "理工", "", "https://www.glut.edu.cn"),
    ("广西医科大学", "广西", "南宁", "医药", "", "https://www.gxmu.edu.cn"),
    ("广西民族大学", "广西", "南宁", "民族", "", "https://www.gxmzu.edu.cn"),
    ("广西中医药大学", "广西", "南宁", "医药", "", "https://www.gxtcmu.edu.cn"),
    ("南宁师范大学", "广西", "南宁", "师范", "", "https://www.nnnu.edu.cn"),
    ("广西科技大学", "广西", "柳州", "理工", "", "https://www.gxust.edu.cn"),
    ("桂林医学院", "广西", "桂林", "医药", "", "https://www.glmc.edu.cn"),
    ("右江民族医学院", "广西", "百色", "医药", "", "https://www.ymun.edu.cn"),
    ("玉林师范学院", "广西", "玉林", "师范", "", "https://www.ylu.edu.cn"),
    ("广西财经学院", "广西", "南宁", "财经", "", "https://www.gxufe.edu.cn"),
    ("北部湾大学", "广西", "钦州", "综合", "", "https://www.bbgu.edu.cn"),
    ("百色学院", "广西", "百色", "综合", "", "https://www.bsuc.edu.cn"),
    ("贺州学院", "广西", "贺州", "综合", "", "https://www.hzu.gx.cn"),
    ("梧州学院", "广西", "梧州", "综合", "", "https://www.gxwzu.edu.cn"),
    ("河池学院", "广西", "河池", "综合", "", "https://www.hcnu.edu.cn"),
    ("桂林航天工业学院", "广西", "桂林", "理工", "", "https://www.guat.edu.cn"),
    ("桂林旅游学院", "广西", "桂林", "综合", "", "https://www.glit.edu.cn"),
    ("广西艺术学院", "广西", "南宁", "艺术", "", "https://www.gxau.edu.cn"),
    ("广西警察学院", "广西", "南宁", "政法", "", "https://www.gxpc.edu.cn"),
    ("广西农业职业技术大学", "广西", "南宁", "农林", "", "https://www.gxavtc.edu.cn"),

    # ===== 云南 =====
    ("云南大学", "云南", "昆明", "综合", "211|双一流", "https://www.ynu.edu.cn"),
    ("昆明理工大学", "云南", "昆明", "理工", "", "https://www.kmust.edu.cn"),
    ("云南师范大学", "云南", "昆明", "师范", "", "https://www.ynnu.edu.cn"),
    ("云南农业大学", "云南", "昆明", "农林", "", "https://www.ynau.edu.cn"),
    ("云南民族大学", "云南", "昆明", "民族", "", "https://www.ynni.edu.cn"),
    ("昆明医科大学", "云南", "昆明", "医药", "", "https://www.kmmu.edu.cn"),
    ("云南财经大学", "云南", "昆明", "财经", "", "https://www.ynufe.edu.cn"),
    ("西南林业大学", "云南", "昆明", "农林", "", "https://www.swfu.edu.cn"),
    ("云南中医药大学", "云南", "昆明", "医药", "", "https://www.ynutcm.edu.cn"),
    ("大理大学", "云南", "大理", "综合", "", "https://www.dali.edu.cn"),
    ("云南艺术学院", "云南", "昆明", "艺术", "", "https://www.ynart.edu.cn"),
    ("云南警官学院", "云南", "昆明", "政法", "", "https://www.ynpsc.edu.cn"),
    ("曲靖师范学院", "云南", "曲靖", "师范", "", "https://www.qjnu.edu.cn"),
    ("玉溪师范学院", "云南", "玉溪", "师范", "", "https://www.yxnu.edu.cn"),
    ("楚雄师范学院", "云南", "楚雄", "师范", "", "https://www.cxtc.edu.cn"),
    ("红河学院", "云南", "红河", "综合", "", "https://www.uoh.edu.cn"),
    ("文山学院", "云南", "文山", "综合", "", "https://www.wsu.edu.cn"),
    ("保山学院", "云南", "保山", "综合", "", "https://www.bsnc.edu.cn"),
    ("昭通学院", "云南", "昭通", "综合", "", "https://www.ztu.edu.cn"),
    ("滇西科技师范学院", "云南", "临沧", "师范", "", "https://www.lcic.edu.cn"),
    ("昆明学院", "云南", "昆明", "综合", "", "https://www.kmu.edu.cn"),
    ("普洱学院", "云南", "普洱", "综合", "", "https://www.peuni.edu.cn"),
    ("滇西应用技术大学", "云南", "大理", "综合", "", "https://www.education.dali.edu.cn"),

    # ===== 贵州 =====
    ("贵州大学", "贵州", "贵阳", "综合", "211|双一流", "https://www.gzu.edu.cn"),
    ("贵州师范大学", "贵州", "贵阳", "师范", "", "https://www.gznu.edu.cn"),
    ("贵州医科大学", "贵州", "贵阳", "医药", "", "https://www.gmc.edu.cn"),
    ("贵州财经大学", "贵州", "贵阳", "财经", "", "https://www.gufe.edu.cn"),
    ("遵义医科大学", "贵州", "遵义", "医药", "", "https://www.zmc.edu.cn"),
    ("贵州中医药大学", "贵州", "贵阳", "医药", "", "https://www.gzy.edu.cn"),
    ("贵州民族大学", "贵州", "贵阳", "民族", "", "https://www.gzmu.edu.cn"),
    ("贵州师范学院", "贵州", "贵阳", "师范", "", "https://www.gznc.edu.cn"),
    ("贵阳学院", "贵州", "贵阳", "综合", "", "https://www.gyu.cn"),
    ("遵义师范学院", "贵州", "遵义", "师范", "", "https://www.zync.edu.cn"),
    ("黔南民族师范学院", "贵州", "都匀", "师范", "", "https://www.sgmtu.edu.cn"),
    ("贵州工程应用技术学院", "贵州", "毕节", "综合", "", "https://www.gues.edu.cn"),
    ("铜仁学院", "贵州", "铜仁", "综合", "", "https://www.gztrc.edu.cn"),
    ("安顺学院", "贵州", "安顺", "综合", "", "https://www.asu.edu.cn"),
    ("凯里学院", "贵州", "凯里", "综合", "", "https://www.kluniv.edu.cn"),
    ("兴义民族师范学院", "贵州", "兴义", "师范", "", "https://www.xynu.edu.cn"),
    ("六盘水师范学院", "贵州", "六盘水", "师范", "", "https://www.lpssy.edu.cn"),
    ("贵州理工学院", "贵州", "贵阳", "理工", "", "https://www.git.edu.cn"),
    ("贵州商学院", "贵州", "贵阳", "财经", "", "https://www.gzcc.edu.cn"),
    ("贵阳康养职业大学", "贵州", "贵阳", "医药", "", "https://www.gykyedu.cn"),

    # ===== 甘肃 =====
    ("兰州大学", "甘肃", "兰州", "综合", "985|211|双一流", "https://www.lzu.edu.cn"),
    ("西北师范大学", "甘肃", "兰州", "师范", "", "https://www.nwnu.edu.cn"),
    ("兰州理工大学", "甘肃", "兰州", "理工", "", "https://www.lut.edu.cn"),
    ("兰州交通大学", "甘肃", "兰州", "理工", "", "https://www.lzjtu.edu.cn"),
    ("甘肃农业大学", "甘肃", "兰州", "农林", "", "https://www.gsau.edu.cn"),
    ("甘肃中医药大学", "甘肃", "兰州", "医药", "", "https://www.gszy.edu.cn"),
    ("兰州财经大学", "甘肃", "兰州", "财经", "", "https://www.lzufe.edu.cn"),
    ("西北民族大学", "甘肃", "兰州", "民族", "", "https://www.xbmu.edu.cn"),
    ("甘肃政法大学", "甘肃", "兰州", "政法", "", "https://www.gsli.edu.cn"),
    ("天水师范学院", "甘肃", "天水", "师范", "", "https://www.tsnc.edu.cn"),
    ("河西学院", "甘肃", "张掖", "综合", "", "https://www.hexu.edu.cn"),
    ("陇东学院", "甘肃", "庆阳", "综合", "", "https://www.ldxy.edu.cn"),
    ("兰州城市学院", "甘肃", "兰州", "综合", "", "https://www.lzcu.edu.cn"),
    ("兰州工业学院", "甘肃", "兰州", "理工", "", "https://www.lzit.edu.cn"),
    ("甘肃民族师范学院", "甘肃", "合作", "师范", "", "https://www.gnun.edu.cn"),
    ("兰州文理学院", "甘肃", "兰州", "综合", "", "https://www.luas.edu.cn"),
    ("甘肃医学院", "甘肃", "平凉", "医药", "", "https://www.plmc.edu.cn"),

    # ===== 宁夏 =====
    ("宁夏大学", "宁夏", "银川", "综合", "211|双一流", "https://www.nxu.edu.cn"),
    ("宁夏医科大学", "宁夏", "银川", "医药", "", "https://www.nxmu.edu.cn"),
    ("北方民族大学", "宁夏", "银川", "民族", "", "https://www.nun.edu.cn"),
    ("宁夏师范学院", "宁夏", "固原", "师范", "", "https://www.nxnu.edu.cn"),
    ("宁夏理工学院", "宁夏", "石嘴山", "理工", "", "https://www.nxist.edu.cn"),
    ("银川能源学院", "宁夏", "银川", "理工", "", "https://www.ycu.edu.cn"),

    # ===== 青海 =====
    ("青海大学", "青海", "西宁", "综合", "211|双一流", "https://www.qhu.edu.cn"),
    ("青海师范大学", "青海", "西宁", "师范", "", "https://www.qhnu.edu.cn"),
    ("青海民族大学", "青海", "西宁", "民族", "", "https://www.qhmu.edu.cn"),
    ("青海卫生职业技术学院", "青海", "西宁", "医药", "", "https://www.qhvc.edu.cn"),

    # ===== 西藏 =====
    ("西藏大学", "西藏", "拉萨", "综合", "211|双一流", "https://www.utibet.edu.cn"),
    ("西藏民族大学", "西藏", "咸阳", "民族", "", "https://www.xzmu.edu.cn"),
    ("西藏农牧学院", "西藏", "林芝", "农林", "", "https://www.xza.edu.cn"),
    ("西藏藏医药大学", "西藏", "拉萨", "医药", "", "https://www.ttmc.edu.cn"),

    # ===== 新疆 =====
    ("新疆大学", "新疆", "乌鲁木齐", "综合", "211|双一流", "https://www.xju.edu.cn"),
    ("石河子大学", "新疆", "石河子", "综合", "211|双一流", "https://www.shzu.edu.cn"),
    ("新疆医科大学", "新疆", "乌鲁木齐", "医药", "", "https://www.xjmu.edu.cn"),
    ("新疆农业大学", "新疆", "乌鲁木齐", "农林", "", "https://www.xjau.edu.cn"),
    ("新疆师范大学", "新疆", "乌鲁木齐", "师范", "", "https://www.xjnu.edu.cn"),
    ("新疆财经大学", "新疆", "乌鲁木齐", "财经", "", "https://www.xjufe.edu.cn"),
    ("塔里木大学", "新疆", "阿拉尔", "综合", "", "https://www.taru.edu.cn"),
    ("新疆艺术学院", "新疆", "乌鲁木齐", "艺术", "", "https://www.xjart.edu.cn"),
    ("伊犁师范大学", "新疆", "伊犁", "师范", "", "https://www.ylsy.edu.cn"),
    ("喀什大学", "新疆", "喀什", "综合", "", "https://www.ksu.edu.cn"),
    ("新疆工程学院", "新疆", "乌鲁木齐", "理工", "", "https://www.xjie.edu.cn"),
    ("昌吉学院", "新疆", "昌吉", "综合", "", "https://www.cjc.edu.cn"),
    ("新疆警察学院", "新疆", "乌鲁木齐", "政法", "", "https://www.xjjc.edu.cn"),

    # ===== 内蒙古 =====
    ("内蒙古大学", "内蒙古", "呼和浩特", "综合", "211|双一流", "https://www.imu.edu.cn"),
    ("内蒙古农业大学", "内蒙古", "呼和浩特", "农林", "", "https://www.imau.edu.cn"),
    ("内蒙古师范大学", "内蒙古", "呼和浩特", "师范", "", "https://www.imnu.edu.cn"),
    ("内蒙古医科大学", "内蒙古", "呼和浩特", "医药", "", "https://www.immu.edu.cn"),
    ("内蒙古工业大学", "内蒙古", "呼和浩特", "理工", "", "https://www.imut.edu.cn"),
    ("内蒙古财经大学", "内蒙古", "呼和浩特", "财经", "", "https://www.imufe.edu.cn"),
    ("内蒙古民族大学", "内蒙古", "通辽", "综合", "", "https://www.imun.edu.cn"),
    ("内蒙古科技大学", "内蒙古", "包头", "综合", "", "https://www.imust.edu.cn"),
    ("赤峰学院", "内蒙古", "赤峰", "综合", "", "https://www.cfxy.edu.cn"),
    ("呼伦贝尔学院", "内蒙古", "呼伦贝尔", "综合", "", "https://www.hlbrc.edu.cn"),
    ("集宁师范学院", "内蒙古", "乌兰察布", "师范", "", "https://www.jntc.edu.cn"),
    ("河套学院", "内蒙古", "巴彦淖尔", "综合", "", "https://www.hetaodx.edu.cn"),
    ("呼和浩特民族学院", "内蒙古", "呼和浩特", "民族", "", "https://www.imnc.edu.cn"),
    ("鄂尔多斯应用技术学院", "内蒙古", "鄂尔多斯", "理工", "", "https://www.oit.edu.cn"),
    ("内蒙古艺术学院", "内蒙古", "呼和浩特", "艺术", "", "https://www.imac.edu.cn"),

    # ===== 海南 =====
    ("海南大学", "海南", "海口", "综合", "211|双一流", "https://www.hainanu.edu.cn"),
    ("海南师范大学", "海南", "海口", "师范", "", "https://www.hainnu.edu.cn"),
    ("海南医科大学", "海南", "海口", "医药", "", "https://www.hainmc.edu.cn"),
    ("海南热带海洋学院", "海南", "三亚", "综合", "", "https://www.qzu.edu.cn"),
    ("三亚学院", "海南", "三亚", "综合", "", "https://www.sanyau.edu.cn"),
    ("海口经济学院", "海南", "海口", "综合", "", "https://www.hkc.edu.cn"),

    # ===== 台湾（代表性院校）=====
    ("台湾大学", "台湾", "台北", "综合", "", "https://www.ntu.edu.tw"),
    ("台湾清华大学", "台湾", "新竹", "综合", "", "https://www.nthu.edu.tw"),
    ("台湾成功大学", "台湾", "台南", "综合", "", "https://www.ncku.edu.tw"),

    # ===== 香港 =====
    ("香港大学", "香港", "香港", "综合", "", "https://www.hku.hk"),
    ("香港中文大学", "香港", "香港", "综合", "", "https://www.cuhk.edu.hk"),
    ("香港科技大学", "香港", "香港", "理工", "", "https://www.ust.hk"),
    ("香港理工大学", "香港", "香港", "理工", "", "https://www.polyu.edu.hk"),
    ("香港城市大学", "香港", "香港", "综合", "", "https://www.cityu.edu.hk"),
    ("香港浸会大学", "香港", "香港", "综合", "", "https://www.hkbu.edu.hk"),
    ("香港岭南大学", "香港", "香港", "综合", "", "https://www.ln.edu.hk"),
    ("香港教育大学", "香港", "香港", "师范", "", "https://www.eduhk.hk"),

    # ===== 澳门 =====
    ("澳门大学", "澳门", "澳门", "综合", "", "https://www.um.edu.mo"),
    ("澳门科技大学", "澳门", "澳门", "综合", "", "https://www.must.edu.mo"),
    ("澳门理工大学", "澳门", "澳门", "理工", "", "https://www.mpu.edu.mo"),

    # ===== 更多知名院校 =====
    ("深圳技术大学", "广东", "深圳", "理工", "", "https://www.sztu.edu.cn"),
    ("上海海关学院", "上海", "上海", "综合", "", "https://www.customs.edu.cn"),
    ("中国社会科学院大学", "北京", "北京", "综合", "", "https://www.ucass.edu.cn"),
    ("上海电机学院", "上海", "上海", "理工", "", "https://www.sdju.edu.cn"),
    ("上海商学院", "上海", "上海", "财经", "", "https://www.sbs.edu.cn"),
    ("上海政法学院", "上海", "上海", "政法", "", "https://www.shupl.edu.cn"),
    ("上海第二工业大学", "上海", "上海", "理工", "", "https://www.sspu.edu.cn"),
    ("上海应用技术大学", "上海", "上海", "理工", "", "https://www.sit.edu.cn"),
    ("上海视觉艺术学院", "上海", "上海", "艺术", "", "https://www.siva.edu.cn"),
    ("上海建桥学院", "上海", "上海", "综合", "", "https://www.gench.edu.cn"),
    ("上海杉达学院", "上海", "上海", "综合", "", "https://www.sandau.edu.cn"),
    ("上海兴伟学院", "上海", "上海", "综合", "", "https://www.xingwei.edu.cn"),
]


def write_universities_csv():
    path = os.path.join(DATA_DIR, "universities.csv")
    with open(path, "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["name", "province", "city", "type", "tags", "website"])
        for uni in UNIVERSITIES:
            writer.writerow(uni)
    print(f"已写入 {len(UNIVERSITIES)} 所大学到 {path}")


if __name__ == "__main__":
    write_universities_csv()
